### ISSUE TITLE
Apple M1 on Monterey getting "Fatal error: Uncaught RedisException" on Pantheon recipes

### ISSUE THREAD

**Issue by mike-scipioni** [lando/pantheon#17]
I'm on an M1 Macbook Pro Max
Docker: 3.6.0
Lando: 3.4.2

I'm able to successfully init and start both a Drupal 7 and Wordpress instance using the Pantheon recipe. However, when I navigate to my URLs I get the following.

**Wordpress**
Fatal error: Uncaught RedisException: Connection refused in /app/wp-content/object-cache.php:974 Stack trace: #0 /app/wp-content/object-cache.php(974): Redis->connect('cache', '6379', 1, NULL, 100)

**Drupal**
Warning: Redis::connect(): connect() failed: Connection refused in /app/sites/all/modules/redis/lib/Redis/Client/PhpRedis.php on line 14

Redis is installed and running via homebrew. I've replaced my Docker with the Apple Silicon version and have tried several versions of that and am currently on 3.6.0. I don't have any firewall running.

I understand that M1 support for Lando is still in the "best effort" phase so I'm wondering if this is simply a symptom of that, or if I'm missing something on my end.

**Comment by reynoldsalec** [comment]
FWIW, I have not had a similar issue running Redis on my M1 Mac (2020 MacBook Pro).

@mike-scipioni I'm going to close this out but feel free to follow-up and I'll try to jump back on it (or ping me on the Lando Slack https://launchpass.com/devwithlando)

**Comment by apotek** [comment]
@reynoldsalec I have same issue and my solution was exactly as @mike-scipioni describes (except I used `redis:6-alpine`). 

I almost finished creating my issue before seeing this closed one. _Why is this closed? I see no commit or PR addressing it._  It seems the default recipe would probably benefit from specifying a more recent version of redis for everyone.  And it would save very very many users hours of troubleshooting if this was fixed in the recipe. 

There is a workaround, but for usability's sake, I think an update to the redis version in the base recipe would be in order. I would be happy to do a PR for that, if that's possible.

Here's the issue I was going to file. 
----

When running `lando start` on a pantheon recipe, a redis 2 container is started. 

On a Mac with the new M1 chip, the redis server crashes immediately upon running its entrypoint, leading to "connection refused" errors. 

This can be fixed by overriding the recipe's default config either in your `.lando.yml` file or `.lando.local.yml`, like so:

```yml
services:
  cache:
    type: redis:6-alpine
```

By specifying a later redis version, we can get a container that will run successfully on the Mac with an M1 chip. 

```
lando redis-cli 
127.0.0.1:6379> keys *
 1) "9.3.3::cachetags:config:system.menu.tools"
 2) "9.3.3::cachetags:config:system.menu.admin"
 3) "9.3.3::cachetags:config:system.menu.account"
 ...
```

Moving from redis 2 to redis 6 changes nothing in Drupal's behavior (which uses only a very basic set of features). 

Can we update the base pantheon recipe so that your users don't have to do the above troubleshooting and overriding? It seems to be a non-breaking change. 

I would be happy to make the pull request if these recipes are forkable.

**Comment by reynoldsalec** [comment]
@apotek recipes are totally forkable and PRs are very much encouraged!

I think the only potential argument against updating the default redis version would be it could wipe out redis data for users on older versions unexpectedly (IE when they rebuild after updating Lando), but given the nature of the redis cache I wouldn't think that would be an issue.

**Comment by apotek** [comment]
> @apotek recipes are totally forkable and PRs are very much encouraged!
> 
> I think the only potential argument against updating the default redis version would be it could wipe out redis data for users on older versions unexpectedly (IE when they rebuild after updating Lando), but given the nature of the redis cache I wouldn't think that would be an issue.

Hi @reynoldsalec ! I took a look at this repo in order to fork and make a pull request, and it doesn't appear that there is any code anywhere in the pantheon plugin that specifies the redis container version. It must be inherited from elsewhere, presumably the base `/lando` repo or `/lando/redis`. 

The one place i see redis versions being set is in `lando/redis/services/redis/builder.js` where it appears to be set to redis 5 by default, which is not what the pantheon recipe seems to set (2.8). 

So I am not sure where or how I would be able to contribute this change. :(

**Comment by reynoldsalec** [comment]
@apotek https://github.com/lando/pantheon/blob/9544135d8465b51d20f2f564b1668832cfae384b/lib/utils.js#L142

**Comment by reynoldsalec** [comment]
I went ahead and put up the PR: #106

Just checking with Pantheon to make sure that Redis v6 won't throw people off...I'm not sure what version they're running on the platform these days.

**Comment by reynoldsalec** [comment]
Hmm, so Pantheon still uses v2.8...was hoping that Lando was behind, but guess Pantheon is just stuck in their ways.

I'm guessing for most Pantheon users it won't matter, but if we make this change in the recipe, I'm sure we'll have a new issue with people who have custom things relying on Redis 2.8 that see local problems.

We may be better off just documenting this solution (updating Redis to 2.8) in an FAQ for now... @pirog you have a gut feel for that?

**Comment by apotek** [comment]
You guys have a little more time on your hands than I do. Thanks for getting to this :). I have to wait for the weekend before I can dig into it.

Here's what I am going to do. 

1. I have been using redis version 6 successfully for Mac OS M1. But I also see that lando defaults to version 5 still (while supporting version 2). I think I should test with version 5 of redis. If that version (5) also has been compiled to an M1 compatible image, then we should probably just align the pantheon recipe with the lando default. 

2. If the test works, I'm happy to help with the PR. 

3. If the test does not work, then I think we should push forward with this update. My thinking on this is simply that the way drupal uses redis is as a very basic getter and setter of cache objects. It doesn't really rely on any new features, and the api for getting and setting objects has been stable for a long time. However, due diligence would suggest that maybe we  try to get some "tested by community" votes on the PR (people using lando w pantheon + d7 and lando w pantheon + d9 on linux and windows and older macs).

**Comment by pirog** [comment]
@apotek that we have more time on our hands is _extremely_ presumptuous :) 

@reynoldsalec FWIW i personally dont think its a great idea to bump from 2.8 to 6 for everyone using the pantheon plugin. that said, we can definitely use a different redis version for just the people on `arm` machines. its not the ideal solution but its an improvement over the existing situation and does not carry any risk to the people on `amd`.

Depending on how long Pantheon plans to continue to support 2.8 we could consider spitting out our own `arm` redis 2.8 image as well.

**Comment by reynoldsalec** [comment]
Good call @pirog, same maneuver as what we did with MariaDB. I just updated [my PR](https://github.com/lando/pantheon/pull/106) to reflect that, going to annoy you about it on Slack since it looks like we have some sort of docs-related error preventing tests from running.

**Comment by apotek** [comment]
Just wanted to say that running redis 5 on my my M1 is working fine. _And_ it is the default version in lando.

So there might be an argument to be made to bump to stay in line with lando itself. 

> i personally dont think its a great idea to bump from 2.8 to 6 for everyone using the pantheon plugin.

I know this doesn't feel great to do intuitively, but so far no has pointed out any concrete reason not to. I don't know of any place where drupal calls the redis api differently, or the api itself is implemented differently for the basic kinds of operations drupal does with object caching.

> that said, we can definitely use a different redis version for just the people on arm machines.

Sounds like a decent way to remove an impediment for many without potentially alienating the (so far) none :)

**Comment by pirog** [comment]
@apotek its less about how it feels and more that it doesnt make sense to me to potentially introduce a breaking change to thousands of developers based on crowdsourcing "i think it should be ok" from this thread especially when the change itself is unnecessary. 

So my opinion would be change the version for `arm` users, its better than what we have now and we can actually put the rubber to the road on testing whether 2.8 -> 5 or 6 actually breaks.

**Comment by apotek** [comment]
@pirog. You are right. While my "I think it should be ok" is based on the fact that there are no breaking changes documented in anything drupal uses, the "it is not safe" is based on .... experience that documentation isn't as accurate as actually running the code. In this case, our experience that reality doesn't meet researched expectations should win.

**Comment by pirog** [comment]
If i had a🍺  for every time i'd been 🔥  by that i'd def be drunk ;)

**Comment by reynoldsalec** [comment]
Awesome, thanks @apotek for sticking with this one, wish I had nailed it down earlier!

Merged in the [PR](https://github.com/lando/pantheon/pull/108), it won't be in the Lando binary until we cut a new release, but until then M1 users can manually insert `redis:6` using @apotek's [example](https://github.com/lando/pantheon/issues/17#issuecomment-1019034919).

**Comment by apotek** [comment]
Thank you @reynoldsalec for making the change and thank you @pirog for guidance!
