### ISSUE TITLE
404 response for POST to user keys

### ISSUE THREAD

**Issue by matbrady** [lando/pantheon#239]
## Issue 

`lando init` fails when requesting `https://terminus.pantheon.io/api/users/REDACTED/keys`. The response returns a 404

```
lando       15:48:03 VERBOSE ==> making post request to https://terminus.pantheon.io/api/users/REDACTED/keys 
lando       15:48:03 DEBUG ==> request sent data with {"headers":{"User-Agent":"Terminus/Lando"}} "ssh-rsa REDACTED lando@REDACTED.fios-router.home" 
lando       15:48:19 ERROR ==> Error: POST request to users/REDACTED/keys failed with code 404: Not Found. The server responded with the message Not found.
```

## Area of Interest

https://github.com/lando/pantheon/blob/3a3ab11527ee7153341b7625af6f3cf3818243a1/lib/client.js#L133-L138

## Machine Details
| Type | version |
| --- | --- |
| Lando | v3.20.8 |
| Terminus | v3.3.5 |

**Comment by reynoldsalec** [comment]
@matbrady this issue was introduced with a change to the Terminus API by Pantheon and resolved by a prompt PR their team made to `lando/pantheon`: https://github.com/lando/pantheon/pull/229

Please update to v1.4.0 or above on the Pantheon plugin; if you're running Lando 3.21+, you can simply run `lando update`.

Going to close this out but LMK if you have issues with the update here or on the Lando Slack. Thanks!
