### ISSUE TITLE
Error with lando init and choosing Pantheon: failed with code 200: undefined

### ISSUE THREAD

**Issue by digisavvy** [lando/pantheon#29]
**Tell us about your setup**
Macbook Pro 2020, 16"

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
Big Sur 11.0.1
Lando v3.0.23 and v3.0.21

**Tell us about your `.lando.yml`**
NA

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

**Tell us about the command you were running**

I was trying to spin up a new website from a Pantheon instance.
I updated to the latest Lando when I noticed the error.

The command I ran was: `lando init`
I chose 'Pantheon' from the list in the following prompt.
I then chose to my pantheon account. After about 20 seconds I received the following error:
`ERROR ==>  request to undefined failed with code 200: undefined. The server responded with the message undefined. `

**What else I tried for troubleshooting**

* I downgraded to v3.0.21 and the error persisted
* I updated terminus to 2.4.1
* I updated composer to v2
* Docker Desktop v2.5.0.1
* I re-ran the command and still had the issue. 
* I created a new machine token and still had the error as well
* 

** Error Log Output **

```
"level":"error","message":" request to undefined failed with code 200: undefined. The server responded with the message undefined.","label":"lando","timestamp":"2020-12-25T07:57:35.065Z"
```

**Comment by reynoldsalec** [comment]
Working with the other user, it may be that their issue is caused by the initial request that Lando makes to Terminus lacking an `application/json` content header. Having them test a PR related to that: https://github.com/lando/pantheon/pull/114

**Comment by reynoldsalec** [comment]
Ok, the `application/json` content header was a red herring, but we did uncover what is likely the root cause of this issue.

In a case where you receive `Error: request to undefined failed with code 200: undefined. The server responded with the message undefined.` (note that you'll need to run `lando init -vvv` to see the specific error), the issue is that an Axios request from Lando's NodeJS binary is failing to communicate with the Pantheon API endpoints.

When `lando init` occurs, Lando doesn't have Terminus installed within a container, so to authenticate and retrieve a site list from Pantheon, it makes a request directly from Lando's standalone NodeJS binary.

It's likely if you receive this error that you're operating in an environment with an SSL decryptor or other proxy that requires its cert to be added to the Node environment. The underlying error in our case was `Error: unable to get local issuer certificate`.

To fix this, your host machine needs to specify the intermediary's cert in the `NODE_EXTRA_CA_CERTS` environmental variable:

```
export NODE_EXTRA_CA_CERTS=/location/of/cert.pem`
```

Further details will be available in a forthcoming [guide article](https://docs.lando.dev/guides/lando-corporate-network-tips.html)

@digisavvy if you ever come back to this would be curious if your problem stemmed from this.
