### ISSUE TITLE
Add IonCube Support

### ISSUE THREAD

**Issue by acobster** [lando/pantheon#46]
Feature Request
===============

Per [discussion](https://kalabox.slack.com/archives/C2XBSHX8R/p1519749520000352) in slack today, it would be great to get IonCube support into Lando's PHP 7.1+ builds. This would provide out-of-the-box support for things like the Memberium plugin.

https://www.ioncube.com/loaders.php

**Comment by roberttolton** [comment]
@infused-kim @tripflex Thank you both for the notes to get it working.

It was working fine on my Intel MacBook Pro, but since transitioning to ARM I get this error:

```
Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20180731/ioncube_loader_lin_7.3.so:  /usr/local/lib/php/extensions/no-debug-non-zts-20180731/ioncube_loader_lin_7.3.so: cannot open shared object file: No such file or directory
```

It doesn't make sense because the file definitely exists, and PHP is running version 7.3 and I'm using version 7.3 of the extension. Any ideas?

**Comment by miquelbrazil** [comment]
Sorry for jumping on an old thread, but I found this while trying to install ioncube on lando for use with the Setasign PDF components. The echo to a first load `ini` worked perfectly.

Also, @roberttolton, not sure if you figured this out, but there is a separate build of the ioncube extension for arm-based linux, which is what you would need to run this in the container.
